spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/tbc?useUnicode=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root

uploadPath:
  excel: /home/data/file/excel

downloadPath:
  excel: /home/data/file/template/data_import_template.xlsx

imgUrl:
  prefix: http://image.baidacapital.com



