server:
  port: 8001
spring:
  application:
    name: mini-program
  profiles:
    active: base,local
  mvc:
    throw-exception-if-no-handler-found: true  #404抛出异常自行处理
  resources:
    add-mappings: true
#    chain:
#      cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
