spring:
  datasource:
    druid:
      url: jdbc:mysql://212.64.6.81:3306/tbc?useUnicode=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root

uploadPath:
  excel: /Users/fuyunhao/Download/file/excel

downloadPath:
  excel: /Users/fuyunhao/Download/file/template/data_import_template.xlsx

imgUrl:
  prefix: http://image.baidacapital.com
