spring:
  datasource:
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: false
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: false
        session-stat-max-count: 1000
        principal-session-name:
        principal-cookie-name:
        profile-enable: true
      stat-view-servlet:
        enabled: false
        url-pattern: /druid/*
        reset-enable: true
        login-username: loan-druid
        login-password: loan-123456
        allow:
        deny:
      filters: stat,wall,config
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/custom/*.xml
  type-aliases-package: com.capital.mini.pojo
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql

logging:
  config: classpath:logback/logback-spring.xml
  level:
    org.springfromework: info
    com.boing: info
